In [1]:
!pip install  watson-machine-learning-client

In [2]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"BPFGcOrCf3sroRy3uKOPGozsmIL-5oVDv4A_lru2IpMS"
    
}

client=APIClient(wml_credentials)

In [3]:
client=APIClient(wml_credentials)

In [4]:
client

In [5]:
 def guid_from_space_name(client, space_name):
     space=client.spaces.get_details()
     #print(space)
     return(next(item for item in space['resources'] if item['entity']['name']== space_name)['metadata']['id'])

In [6]:
space_uid=guid_from_space_name(client,'imageclassification') #imageclassification is the deployment space name
print("Space UID ="+space_uid)

Space UID =ba02adea-7e10-4237-81e7-eaf084fe4102


In [7]:
client.set.default_space(space_uid)

'SUCCESS'

In [9]:
client.repository.download("f3e12114-24f4-4bae-9d60-2897d27e7ce6", 'nutrition.tar.gz')

Successfully saved model content to file: 'nutrition.tar.gz'


'C:\\Users\\karup\\Downloads/nutrition.tar.gz'

In [10]:
from keras.models import load_model
from keras.preprocessing import image

In [11]:
model = load_model("nutrition.h5")

In [13]:
import numpy as np

In [14]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("apple.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 1s 696ms/step


array([0], dtype=int64)

In [15]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'APPLES'

In [16]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("banana.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 40ms/step


array([1], dtype=int64)

In [17]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'BANANA'

In [20]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("Test_Image5.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 40ms/step


array([3], dtype=int64)

In [21]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'PINEAPPLE'